### PR TITLE
Remove python 3.8 support

### PR DESCRIPTION
**Pull request by jjaakola-aiven**
# About this change - What it does
Remove support for Python 3.8, it is EOL.

### CODE REVIEW

**Review by keejon — DISMISSED** [review]
Nice 👍

**Comment by aiven-anton** [comment]
pyupgrade can also be bumped after this: https://github.com/Aiven-Open/karapace/blob/a4030fecfd202fd6489d1f50703ce7ba023f71eb/.pre-commit-config.yaml#L37

**Comment by jjaakola-aiven** [comment]
@aiven-anton I'll change to `py39`, no reason the leave these pending another PR.

**Review by keejon — APPROVED** [review]
LGTM 👍

**Pull request merged**
