### PR TITLE
tests,backup: fix flakiness by using current timestamps

### PR DESCRIPTION
**Pull request by davide-armand**
Using some (old) fixed timestamps when producing messages was causing the
messages to be automatically deleted because past message retention.

I think most of the time the test was managing to complete successfully
before the retention kicked in, making it fail only sometimes.

### CODE REVIEW

**Comment by aiven-anton** [comment]
Nice finding, I guess alternative fix could be to disable retention? (Asking because we most likely have the exact same issue here: https://github.com/aiven/backups-for-apache-kafka/issues/26)

**Review by eliax1996 — APPROVED** [review]
LGTM, great finding. How did you realized it?

**Comment by davide-armand** [comment]
> Nice finding, I guess alternative fix could be to disable retention? (Asking because we most likely have the exact same issue in an internal project)

Ah yes I guess that would work too, did no think about that

**Comment by davide-armand** [comment]
> LGTM, great finding. How did you realized it?

@eliax1996 The beginning offset of the topic was mysteriously changing from 0 to the 2 (end offset) after a few seconds.
Doing `consumer.seek` to offset 0 was failing.
Then I simplified the test until I found out about the timestamps..

**Pull request merged**
