### PR TITLE
Add support for '-1' as version

### PR DESCRIPTION
**Pull request by mattieserver**
# About this change - What it does
This allows adding '-1' as the version just like 'latest'.

References: #668

# Why this way

This seems like the quickest way to add support for the '-1'

### CODE REVIEW

**Review by jjaakola-aiven — COMMENTED** [review]
This is the easiest way to add the `-1` support. I'd prefer to move the responsibility of resolving to a `Version` class and the validation of the input string closer to the REST API. That would mean a bit more of refactoring:
 * Move `karapace.typing.Version` to `karapace.schema_models.Version`
 * Change to a class and implement the resolving and validation.
 * Change the `_resolve_version` calls `version.resolve(schema_versions)`.
 * Create the version objects from the input string in `karapace.schema_registry_api`.
 * Add tests

**Comment by mattieserver** [comment]
I expected something like this 😄 

I try to implement the changes like you requested.

**Comment by aiven-anton** [comment]
This should possibly be kept in sync with the respective handling here: https://github.com/Aiven-Open/karapace/blob/4ab7e9e3dfe64544117fdce594c742175e15b8e6/karapace/schema_reader.py#L572

**Comment by nosahama** [comment]
#668 will be fixed with #885, closing this PR.

**Pull request closed without merging**
